# Generated by Django 2.1.5 on 2019-06-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('function', models.CharField(max_length=255)),
                ('config', models.TextField(help_text='in JSON')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.TextField()),
                ('solution', models.TextField()),
                ('code', models.CharField(max_length=255)),
                ('hints', models.TextField(blank=True)),
                ('correct', models.TextField(blank=True)),
                ('incorrect', models.TextField(blank=True)),
                ('commands', models.ManyToManyField(blank=True, related_name='riddle', to='core.Command')),
            ],
            options={
                'verbose_name_plural': 'Riddles',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, choices=[('EASY', 'Leicht'), ('MEDIUM', 'Mittel'), ('DIFFICULT', 'Schwer')], default='MEDIUM', max_length=255)),
                ('length', models.DurationField(blank=True, default='00:30:00')),
                ('riddles', models.ManyToManyField(related_name='scenario', to='core.Riddle')),
            ],
            options={
                'verbose_name_plural': 'Scenarios',
            },
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Device')),
                ('lamp_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('on', models.BooleanField(default=False)),
                ('color', models.CharField(default='#ffffff', help_text='hex-value, default white', max_length=7)),
                ('room', models.CharField(blank=True, max_length=255)),
                ('brightness', models.IntegerField(blank=True, default=254, help_text='254 = 100%, 127 = 50%, ...')),
            ],
            bases=('core.device',),
        ),
        migrations.AddField(
            model_name='command',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='device', to='core.Device'),
        ),
    ]
