# Generated by Django 2.1.5 on 2019-07-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hueremotecontrol',
            old_name='lamp_id',
            new_name='control_id',
        ),
        migrations.RemoveField(
            model_name='hueremotecontrol',
            name='room',
        ),
    ]
