# Generated by Django 2.1.5 on 2019-07-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190714_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='knxlamp',
            name='group_adddress',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
