# Generated by Django 2.1.5 on 2019-07-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knxlamp_group_adddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='protocol',
            field=models.CharField(choices=[('KNX', 'knx'), ('PHue', 'philips hue')], default='KNX', max_length=255),
            preserve_default=False,
        ),
    ]
