# Generated by Django 2.1.5 on 2019-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190623_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='code',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='correct',
            field=models.TextField(blank=True, default='Grandios, dass war richtig.'),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='incorrect',
            field=models.TextField(blank=True, default='Schade, dass war leider falsch, versuch es doch nochmal.'),
        ),
    ]
