# Generated by Django 2.1.5 on 2019-07-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_command_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusMotor',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Device')),
                ('device_address', models.IntegerField()),
            ],
            bases=('core.device',),
        ),
        migrations.AddField(
            model_name='activescenario',
            name='box',
            field=models.BooleanField(blank=True, default=True, help_text='"true": box ist offen, "false": box ist geschlossen', null=True),
        ),
    ]
