# Generated by Django 2.1.5 on 2019-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190715_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='loop',
            field=models.IntegerField(default=99, help_text='0 (only once) - 99 (infinity)'),
        ),
        migrations.AlterField(
            model_name='activescenario',
            name='box',
            field=models.BooleanField(blank=True, default=False, help_text='"true": box ist offen, "false": box ist geschlossen', null=True),
        ),
    ]
