# Generated by Django 2.1.5 on 2019-07-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activescenario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='code',
            field=models.IntegerField(),
        ),
    ]
