# Generated by Django 2.1.5 on 2019-07-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190701_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescenario',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_scenarios', to='core.Scenario'),
        ),
        migrations.AlterField(
            model_name='activescenario',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
