# Generated by Django 2.1.5 on 2019-07-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190716_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='knxshutter',
            name='group_adddress',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='command', through='core.OrderedAction', to='core.Action'),
        ),
        migrations.AlterField(
            model_name='command',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='command', to='core.Device'),
        ),
    ]
