# Generated by Django 2.1.5 on 2019-07-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190701_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescenario',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
