# Generated by Django 2.1.5 on 2019-07-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190701_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='activescenario',
            name='riddle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_riddles', to='core.Riddle'),
        ),
    ]
