# Generated by Django 2.1.5 on 2019-07-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_activescenario_riddle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescenario',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
