# Generated by Django 2.1.5 on 2019-07-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190703_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activescenario',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
