# Generated by Django 2.1.5 on 2019-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_scenario_other_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='color',
            field=models.CharField(choices=[('MAGENTA', 'FF00FF'), ('RED', 'ff0000'), ('ORGANGE', 'ffa500'), ('YELLOW', 'f5ff00'), ('BLUE', '0000ff'), ('CYAN', '00ffff'), ('GREEN', '00f700'), ('WHITE', 'ffffff')], default='WHITE', help_text='hex-value, default white', max_length=7),
        ),
    ]
