# Generated by Django 2.1.5 on 2019-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190707_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='color',
            field=models.CharField(choices=[('FF00FF', 'MAGENTA'), ('ff0000', 'RED'), ('ffa500', 'ORGANGE'), ('f5ff00', 'YELLOW'), ('0000ff', 'BLUE'), ('00ffff', 'CYAN'), ('00f700', 'GREEN'), ('ffffff', 'WHITE')], default='WHITE', help_text='hex-value, default white', max_length=7),
        ),
    ]
